### ISSUE TITLE
Gazebo not finding model and world directory

### ISSUE THREAD

**Issue by xela-95** [vvv-school/tutorial_gazebo-simple-model#1]
I'm trying to reproduce this tutorial by using a conda environment created in the following way:

```
mamba create -c conda-forge -c robotology -n yarp_tutorials_env  cmake ninja pkg-config make compilers yarp icub-contrib-common gazebo icub-models gazebo-yarp-plugins idyntree
```

I've built and installed the code and that went fine. The issue is that Gazebo does not find the model used in the tutorial, neither from the "Insert" pane nor spawning the world file with `gazebo simple_object_world.sdf`.

I think the issue is due to the fact that the model directory is installed in `<conda-env-path>/share/gazebo/models` while the GAZEBO_MODEL_PATH environment variable has value `<conda-env-path>/share/gazebo-11/models`. 

Do I have made any mistake in the conda environment creation or do I miss some configuration?

**Comment by xela-95** [comment]
I tried to add in my `.bashrc` file the missing path to the `GAZEBO_MODEL_PATH` env variable:
```bash
export GAZEBO_MODEL_PATH=${GAZEBO_MODEL_PATH}:<conda-env-path>/share/gazebo/models
```

Then, launching Gazebo I'm able to see the model in the insert pane:
![Screenshot from 2024-01-04 16-58-00](https://github.com/robotology/gz-sim-yarp-plugins/assets/57228872/c0485779-e900-40b1-ae8f-3039ac8164c8)

**Comment by traversaro** [comment]
This is related to https://github.com/robotology/robotology-superbuild/issues/1563 .
